### ISSUE TITLE
_ and () are not parsed in library slug field

### ISSUE THREAD

**Issue by olli-suutari-jkl** [libraries-fi/kirkanta#17]
Due to the recent changes in slug (url-tunniste) validation, the field no longer accepts () and _ in their values.

This leads to a validation error if forbidden characters are present, when the user tries to save the basic details after modifying other details.

"_" should be parsed to "-" , "(" to "" and ")" to "".
Validation error is probably also triggered for other forbidden values, such as "ä".  

Something like this could be used for the parsing:
https://github.com/olli-suutari-jkl/jyvaskyla.fi.kirjasto/blob/d9a2a73d340adbbb1447f22667a28bcb21cd21b5/js/getParameters.js#L64

![image](https://user-images.githubusercontent.com/42733913/61636039-7f792700-ac9d-11e9-8b9c-0efb2ced1ffc.png)

![image](https://user-images.githubusercontent.com/42733913/61636053-87d16200-ac9d-11e9-8e3d-a576de630530.png)

**Comment by sjuvonen** [comment]
I don't think it's a recent change but just that in the old admin interface slug was both behind a rarely accessed tab but also hidden from regular users. Actually the slug should also now be hidden from regular users as it is something that should be changed only after a careful assessment (because it breaks bookmarks/links to Kirjastohakemisto). 

There is support for user permission check inside the form builder so I am not sure why it was left unimplemented. Probably because slug is generated client-side when creating a new library so the field has to be present in one form or another, but it could be made read-only using the HTML5 attribute.

Invalid slugs should probably be fixed into the DB because slug conflict checks also depend on the DB being populated correctly.

There was a plan, actually, to re-generate all slugs since the old algorithm always appended a junk string to avoid conflicts but we should really prefer slugs as short as possible while also preserving meaningfulness.

**Comment by olli-suutari-jkl** [comment]
Feedback from Multia:
". Niitä tallennettaessa sivusto herjaa URL-tunnisteen olevan väärässä muodossa, ja näyttäisi olevankin, siinä käytetään alaviivaa eikä viivaa (dash). Nyt tunniste on siis multian_kirjasto. Sitä ei kuitenkaan kukaan ole muuttanut, vaan on ollut kai aina tuollainen. Muuttamisesta taas varoitetaan, että se rikkoo selaimen kirjanmerkit. Onko se paha? Slogan ja kuvaus eivät näyttäisi tallentuvan, ellei tuolle tee jotain."

**Comment by humble-ahitofel** [comment]
Although it is recommended, that dashes - should be used instead of underscore _, I think we should allow using underscores in the slug for know, because it is hard to enforce usage of dashes if the underscore slugs exist in the database. I'll make the changes needed, so underscore is allowed in the slug.

**Comment by sjuvonen** [comment]
Meh, I replaced the underscores with dashes. There are many other problems with the slugs, so they should be re-generated properly at some other time...

**Comment by humble-ahitofel** [comment]
Very well, then no changes are needed then to source code. I'm closing this issue.
